-- create-posts-table
CREATE TABLE public.posts (
    id BIGINT NOT NULL,
    content TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'PUBLIC'
        CHECK (status IN ('PUBLIC', 'PRIVATE')),
    user_id BIGINT NOT NULL,
    original_post_id BIGINT,
    vote_count INT DEFAULT 0,
    comment_count INT DEFAULT 0,
    share_count INT DEFAULT 0,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

-- Tạo identity cho cột id
ALTER TABLE public.posts
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.posts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
);

-- Khóa chính
ALTER TABLE ONLY public.posts
    ADD CONSTRAINT posts_pkey PRIMARY KEY (id);

-- Ràng buộc khóa ngoại: user_id -> accounts(id)
ALTER TABLE public.posts
    ADD CONSTRAINT fk_posts_user FOREIGN KEY (user_id)
        REFERENCES public.accounts(id) ON DELETE CASCADE;

-- Ràng buộc khóa ngoại: original_post_id -> posts(id)
ALTER TABLE public.posts
    ADD CONSTRAINT fk_posts_original FOREIGN KEY (original_post_id)
        REFERENCES public.posts(id) ON DELETE SET NULL;

-- Tạo chỉ mục cho cột user_id để tăng hiệu suất truy vấn
CREATE INDEX idx_posts_user_id ON public.posts(user_id);

-- create-post-media-table
CREATE TABLE public.post_medias (
    id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    file_type VARCHAR(20) NOT NULL CHECK (file_type IN ('IMAGE', 'VIDEO')),
    object_key TEXT NOT NULL,
    media_index INT DEFAULT 0,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

-- Tạo identity cho cột id
ALTER TABLE public.post_medias
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_medias_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
);

-- Khóa chính
ALTER TABLE ONLY public.post_medias
    ADD CONSTRAINT post_media_pkey PRIMARY KEY (id);

-- Ràng buộc khóa ngoại: post_id -> posts(id)
ALTER TABLE public.post_medias
    ADD CONSTRAINT fk_media_post FOREIGN KEY (post_id)
        REFERENCES public.posts(id) ON DELETE CASCADE;

-- Tạo chỉ mục cho cột post_id để tăng hiệu suất truy vấn
CREATE INDEX idx_post_medias_post_id ON public.post_medias(post_id);

-- Tạo Unique constraint để tránh trùng lặp index cho mỗi post
ALTER TABLE public.post_medias
    ADD CONSTRAINT uq_post_media_post_index UNIQUE (post_id, media_index);

-- create-post-votes-table
CREATE TABLE public.post_votes (
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

-- Tạo khóa chính
ALTER TABLE public.post_votes
    ADD CONSTRAINT pk_post_votes PRIMARY KEY (post_id, user_id);

-- Ràng buộc khóa ngoại: post_id -> posts(id)
ALTER TABLE public.post_votes
    ADD CONSTRAINT fk_post_votes_posts FOREIGN KEY (post_id)
        REFERENCES public.posts(id) ON DELETE CASCADE;

-- Ràng buộc khóa ngoại: user_id -> accounts(id)
ALTER TABLE public.post_votes
    ADD CONSTRAINT fk_post_votes_user FOREIGN KEY (user_id)
        REFERENCES public.accounts(id) ON DELETE CASCADE;

CREATE TABLE public.comments (
    id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    content TEXT,
    object_key TEXT,
    vote_count INT DEFAULT 0,
    reply_count INT DEFAULT 0,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

-- Khóa chính
ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);

-- Tạo identity cho cột id
ALTER TABLE public.comments
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
);

-- Ràng buộc khóa ngoại: post_id -> posts(id)
ALTER TABLE public.comments
    ADD CONSTRAINT fk_comment_post FOREIGN KEY (post_id)
        REFERENCES public.posts(id) ON DELETE CASCADE;

-- Ràng buộc khóa ngoại: user_id -> accounts(id)
ALTER TABLE public.comments
    ADD CONSTRAINT fk_comment_user FOREIGN KEY (user_id)
        REFERENCES public.accounts(id) ON DELETE CASCADE;

CREATE TABLE public.replies (
    id BIGINT NOT NULL,
    comment_id BIGINT NOT NULL,
    reply_user_id BIGINT NULL,
    user_id BIGINT NOT NULL,
    content TEXT,
    object_key TEXT,
    vote_count INT DEFAULT 0,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

-- Primary key
ALTER TABLE ONLY public.replies
    ADD CONSTRAINT replies_pkey PRIMARY KEY (id);

-- Tạo identity cho cột id
ALTER TABLE public.replies
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.replies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
);

-- FK: reply -> comment cha
ALTER TABLE public.replies
    ADD CONSTRAINT fk_reply_comment FOREIGN KEY (comment_id)
        REFERENCES public.comments(id) ON DELETE CASCADE;

-- FK: reply -> user
ALTER TABLE public.replies
    ADD CONSTRAINT fk_reply_user FOREIGN KEY (user_id)
        REFERENCES public.accounts(id) ON DELETE CASCADE;

ALTER TABLE public.replies
    ADD CONSTRAINT fk_reply_user_id
        FOREIGN KEY (reply_user_id)
            REFERENCES public.accounts(id) ON DELETE CASCADE;

-- create-comment-votes-table
CREATE TABLE public.comment_votes (
    comment_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

-- Tạo khóa chính
ALTER TABLE public.comment_votes
    ADD CONSTRAINT pk_comment_votes PRIMARY KEY (comment_id, user_id);

-- Ràng buộc khóa ngoại: comment_id -> comments(id)
ALTER TABLE public.comment_votes
    ADD CONSTRAINT fk_comment_votes_comments FOREIGN KEY (comment_id)
        REFERENCES public.comments(id) ON DELETE CASCADE;

-- Ràng buộc khóa ngoại: user_id -> accounts(id)
ALTER TABLE public.comment_votes
    ADD CONSTRAINT fk_comment_votes_user FOREIGN KEY (user_id)
        REFERENCES public.accounts(id) ON DELETE CASCADE;

-- create-comment-votes-table
CREATE TABLE public.reply_votes (
    reply_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

-- Tạo khóa chính
ALTER TABLE public.reply_votes
    ADD CONSTRAINT pk_reply_votes PRIMARY KEY (reply_id, user_id);

-- Ràng buộc khóa ngoại: reply_id -> replies(id)
ALTER TABLE public.reply_votes
    ADD CONSTRAINT fk_reply_votes_replies FOREIGN KEY (reply_id)
        REFERENCES public.replies(id) ON DELETE CASCADE;

-- Ràng buộc khóa ngoại: user_id -> accounts(id)
ALTER TABLE public.reply_votes
    ADD CONSTRAINT fk_reply_votes_user FOREIGN KEY (user_id)
        REFERENCES public.accounts(id) ON DELETE CASCADE;

