--Create table Conversation
CREATE TABLE public.conversations (
    id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

ALTER TABLE public.conversations
    ADD CONSTRAINT pk_conversations PRIMARY KEY (id);

ALTER TABLE public.conversations
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conversations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
);

CREATE TABLE public.conversation_member_status (
    conversation_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    delete_until_message_id BIGINT NULL,
    last_message_id BIGINT NULL,
    unread_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

ALTER TABLE public.conversation_member_status
    ADD CONSTRAINT pk_conversation_member_status PRIMARY KEY (conversation_id, account_id);

ALTER TABLE public.conversation_member_status
    ADD CONSTRAINT fk_cms_conversation_id
        FOREIGN KEY (conversation_id)
            REFERENCES public.conversations(id)
            ON DELETE CASCADE;

ALTER TABLE public.conversation_member_status
    ADD CONSTRAINT fk_cms_account_id
        FOREIGN KEY (account_id)
            REFERENCES public.accounts(id)
            ON DELETE CASCADE;


-- Create table for messages
CREATE TABLE public.messages (
    id BIGINT NOT NULL,
    conversation_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    message_type VARCHAR(20) NOT NULL CHECK (message_type IN ('MESSAGE','IMAGE', 'VIDEO', 'FILE', 'AUDIO')),
    content TEXT,
    file_name VARCHAR(100),
    object_key TEXT,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

ALTER TABLE public.messages
    ADD CONSTRAINT pk_messages PRIMARY KEY (id);


ALTER TABLE public.messages
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
);

ALTER TABLE public.messages
    ADD CONSTRAINT fk_messages_conversation_id FOREIGN KEY (conversation_id) REFERENCES public.conversations(id) ON DELETE CASCADE;

ALTER TABLE public.messages
    ADD CONSTRAINT fk_messages_account_id FOREIGN KEY (sender_id) REFERENCES public.accounts(id) ON DELETE CASCADE;